### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [jenspfahl/BDT#18]
https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/10065351325

Could you please take a look? Thanks!

**Comment by jenspfahl** [comment]
Locally on my machine a 'flutter clean' solved it. Could this be added to the build script? Or is this already present?

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/jobs/10068818824

It doesn't work. How does the dart version specified?

**Comment by jenspfahl** [comment]
Ok, this is something else

> You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is not possible anymore. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/to/flutter-gradle-plugin-apply
* Try:

I'll have a look later today or tomorrow.

**Comment by jenspfahl** [comment]
Ok, this is something else

> You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is not possible anymore. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/to/flutter-gradle-plugin-apply


Which flutter version is used? It should be 3.22

**Comment by linsui** [comment]
Yes, it's 3.22.

**Comment by jenspfahl** [comment]
I pushed a new commit and updated tag v1.3.0. Does the pipeline take it automatically?

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/jobs/10069513993

**Comment by jenspfahl** [comment]
I updated the failing dependency, hope it helps.

**Comment by licaon-kter** [comment]
@jenspfahl still fails https://gitlab.com/fdroid/fdroiddata/-/jobs/10070933909#L1003

**Comment by jenspfahl** [comment]
Is the 

/home/vagrant/build/de.jepfa.bdt/.pub-cache

directory cleared before building? I am trying to reproduce the error locally. 

Which Dart and Java/Kotlin version is used?

**Comment by jenspfahl** [comment]
@licaon-kter ☝️

**Comment by linsui** [comment]
Yes. The default dart version of the flutter version is used. And jdk 17 is installed by default.

**Comment by licaon-kter** [comment]
> directory cleared before building?

it's a clean VM everytime

**Comment by jenspfahl** [comment]
@licaon-kter Is there a way to build with Flutter 3.27? In version 3.29 a few dependencies have been removed which breaks the build.

**Comment by licaon-kter** [comment]
sure, but how about you take note of the used version in https://github.com/jenspfahl/BDT/blob/v1.3.0/pubspec.yaml#L22 and we use that to match yours?

we bumped it to 3.29 because 3.22 failed, see first link

**Comment by licaon-kter** [comment]
sure, starting now: https://gitlab.com/fdroid/fdroiddata/-/jobs/10078312431
